### PR TITLE
chore: optimize publish related settings

### PR DESCRIPTION
**Pull request by LoTwT**
Try to solve #10.

Please check. :)

### CODE REVIEW

**Review by CatsJuice — APPROVED** [review]
I was initially quite concerned about altering the directory structure of the released files, but I believe your modifications are entirely appropriate. Thx a lot!

**Comment by LoTwT** [comment]
> I was initially quite concerned about altering the directory structure of the released files, but I believe your modifications are entirely appropriate. Thx a lot!

😆

**Comment by CatsJuice** [comment]
@LoTwT 

However, it suddenly dawned on me that changing the structure of the product would render existing CDN links (such as unpkg) ineffective. Also, in the build scripts, some manipulations would actually be done on the `package.json`, such as removing `devDependencies`. So this change may cause a breaking change.

**Comment by CatsJuice** [comment]
So I’m saying that was the initial mistake I made in the design, I’m really sorry. But do you have any other solutions, or is my only option to revert this PR back to its previous state?

**Comment by LoTwT** [comment]
> So I’m saying that was the initial mistake I made in the design, I’m really sorry. But do you have any other solutions, or is my only option to revert this PR back to its previous state?

Sorry for my rough PR. It may be the best choice to revert it.

**Comment by CatsJuice** [comment]
Never mind. The main issue was that I didn’t design it well from the start. I deeply appreciate your proposal though, it has given me a lot of inspiration.

**Pull request merged**
